export default {
  title: 'TypeScript with Vue.js 3',
  courseImage:
    'https://camo.githubusercontent.com/a9716a3c9a63dcb99a27e4d7d13118cdb0bd0581d513d1f55230ac9161660ed2/68747470733a2f2f7675657363686f6f6c2e696f2f6d656469612f38353764373265383266623061303937616436326233396236313638313762312f747970657363726970742d776974682d7675652d6a732d332e6a7067',
  description:
    'Unlock the full potential of Vue.js 3 with the power and safety of TypeScript in this comprehensive course. Dive into the world of modern frontend development as you master the art of building robust and scalable web applications.',
  chapters: [
    {
      title: 'Chapter 1',
      slug: '1-chapter-1',
      number: 1,
      lessons: [
        {
          title: 'Introduction to TypeScript with Vue.js 3',
          slug: '1-introduction-to-typescript-with-vue-js-3',
          number: 1,
          downloadUrl: 'https://vueschool.io/lessons/introduction-to-typescript-with-vue-js-3',
          videoId: 684236333,
          text: `In this lesson, we take a look at some of the benefits of using TypeScript with Vue.js including:

Improved error detection in your IDE and at build time
Safer and less stressful refactoring
More focused and accurate IDE autocompletion

We also answer the question: “Are there any cases when you wouldn’t want to use TypeScript?”.`,
          timeDuration: '9min',
          status: 'complete',
          points: 20,
        },
        {
          title: 'TypeScript in Vue Components',
          slug: '2-typescript-in-vue-components',
          number: 2,
          downloadUrl: 'https://vueschool.io/lessons/typescript-in-vue-components',
          videoId: 684012498,
          text: `In this lesson, we learn how to direct Vue Single File Components to work with typescript.`,
          timeDuration: '6min',
          status: 'pending',
          points: 5,
        },
        {
          title: 'Typing Component Events',
          slug: '3-typing-component-events',
          number: 3,
          downloadUrl: 'https://vueschool.io/lessons/typing-component-events',
          sourceUrl: 'https://vueschool.io/lessons/typing-component-events',
          videoId: 686921522,
          text: `In this lesson, we learn how to type the payload of component events in Vue and TypeScript.`,
          timeDuration: '8min',
          status: 'pending',
          points: 10,
        },
        {
          title: 'Quiz',
          slug: 'quiz1',
          number: 4,
          downloadUrl: 'https://vueschool.io/lessons/typing-component-events',
          sourceUrl: 'https://vueschool.io/lessons/typing-component-events',
          videoId: '',
          text: `What is vue composition API`,
          timeDuration: '8min',
          status: 'pending',
          points: 15,
        },
      ],
    },
    {
      title: 'Chapter 2',
      slug: '2-chapter-2',
      number: 2,
      lessons: [
        {
          title: 'Using TypeScript with the Options API in Components',
          slug: '1-using-typescript-with-the-options-api-in-components',
          number: 1,
          downloadUrl: 'https://vueschool.io/lessons/using-typescript-with-the-options-api-in-components',
          sourceUrl: 'https://vueschool.io/lessons/using-typescript-with-the-options-api-in-components',
          videoId: 688503389,
          text: `In this lesson, we learn how to use TypeScript with the Vue.js Options API to type things such as component props, computed props, and events.`,
          timeDuration: '60min',
          status: 'complete',
          points: 25,
        },
        {
          title: 'Declaring and Typing Component Props',
          slug: '2-declaring-and-typing-component-props',
          number: 2,
          downloadUrl: 'https://vueschool.io/lessons/declaring-and-typing-component-props',
          sourceUrl: 'https://vueschool.io/lessons/declaring-and-typing-component-props',
          videoId: 688500728,
          text: `In this lesson, we’ll examine how to use TypeScript to define types for Vue component props. Along the way, you’ll also get a first hand look at the great DX this provides for interacting with those components.`,
          timeDuration: '45min',
          status: 'pending',
          points: 8,
        },
        {
          title: 'TypeScript in Vue Components',
          slug: '3-typescript-in-vue-components',
          number: 3,
          downloadUrl: 'https://vueschool.io/lessons/typescript-in-vue-components',
          videoId: 684012498,
          text: `In this lesson, we learn how to direct Vue Single File Components to work with typescript.`,
          timeDuration: '35min',
          status: 'complete',
          points: 16,
        },
        {
          title: 'Typing Component Events',
          slug: '4-typing-component-events',
          number: 4,
          downloadUrl: 'https://vueschool.io/lessons/typing-component-events',
          sourceUrl: 'https://vueschool.io/lessons/typing-component-events',
          videoId: 686921522,
          text: `In this lesson, we learn how to type the payload of component events in Vue and TypeScript.`,
          timeDuration: '10min',
          status: 'pending',
          points: 22,
        },
        {
          title: 'Quiz',
          slug: 'quiz2',
          number: 4,
          downloadUrl: 'https://vueschool.io/lessons/typing-component-events',
          sourceUrl: 'https://vueschool.io/lessons/typing-component-events',
          videoId: '',
          text: `What is vue composition API`,
          timeDuration: '8min',
          status: 'pending',
          points: 15,
        },
      ],
    },
    {
      title: 'Chapter 3',
      slug: '3-chapter-3',
      number: 3,
      lessons: [
        {
          title: 'Using TypeScript with the Options API in Components',
          slug: '1-using-typescript-with-the-options-api-in-components',
          number: 1,
          downloadUrl: 'https://vueschool.io/lessons/using-typescript-with-the-options-api-in-components',
          sourceUrl: 'https://vueschool.io/lessons/using-typescript-with-the-options-api-in-components',
          videoId: 688503389,
          text: `In this lesson, we learn how to use TypeScript with the Vue.js Options API to type things such as component props, computed props, and events.`,
          timeDuration: '25min',
          status: 'pending',
          points: 12,
        },
        {
          title: 'Declaring and Typing Component Props',
          slug: '2-declaring-and-typing-component-props',
          number: 2,
          downloadUrl: 'https://vueschool.io/lessons/declaring-and-typing-component-props',
          sourceUrl: 'https://vueschool.io/lessons/declaring-and-typing-component-props',
          videoId: 688500728,
          text: `In this lesson, we’ll examine how to use TypeScript to define types for Vue component props. Along the way, you’ll also get a first hand look at the great DX this provides for interacting with those components.`,
          timeDuration: '40min',
          status: 'pending',
          points: 10,
        },
        {
          title: 'TypeScript in Vue Components',
          slug: '3-typescript-in-vue-components',
          number: 3,
          downloadUrl: 'https://vueschool.io/lessons/typescript-in-vue-components',
          videoId: 684012498,
          text: `In this lesson, we learn how to direct Vue Single File Components to work with typescript.`,
          timeDuration: '8min',
          status: 'pending',
          points: 5,
        },
        {
          title: 'Typing Component Events',
          slug: '4-typing-component-events',
          number: 4,
          downloadUrl: 'https://vueschool.io/lessons/typing-component-events',
          sourceUrl: 'https://vueschool.io/lessons/typing-component-events',
          videoId: 686921522,
          text: `In this lesson, we learn how to type the payload of component events in Vue and TypeScript.`,
          timeDuration: '20min',
          status: 'pending',
          points: 8,
        },
        {
          title: 'Practical 03',
          slug: 'Create a demo project with a POS system',
          number: 5,
          downloadUrl: 'https://vueschool.io/lessons/typing-component-events',
          sourceUrl: 'https://vueschool.io/lessons/typing-component-events',
          videoId: 686921522,
          text: `In this lesson, we learn how to type the payload of component events in Vue and TypeScript.`,
          timeDuration: '30min',
          status: 'pending',
          points: 14,
        },
        {
          title: 'Quiz',
          slug: 'quiz3',
          number: 6,
          downloadUrl: 'https://vueschool.io/lessons/typing-component-events',
          sourceUrl: 'https://vueschool.io/lessons/typing-component-events',
          videoId: '',
          text: `What is vue composition API`,
          timeDuration: '8min',
          status: 'pending',
          points: 15,
        },
      ],
    },
  ],
}
